# Generated by Django 5.2.8 on 2025-11-28 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gc_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gcuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
