# Generated by Django 5.2.8 on 2025-11-28 22:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gc_users", "0002_alter_gcuser_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A human-readable name for this API key.",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Route",
                "verbose_name_plural": "API Routes",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A human-readable name for this API key.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The unique API key used for authentication.",
                        max_length=64,
                        unique=True,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Optional static IP address. If set, requests must come from this IP.",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="The date and time when this API key becomes valid.",
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when this API key expires.",
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether this API key is currently active.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "routes",
                    models.ManyToManyField(
                        blank=True,
                        to="gc_users.apiroute",
                        verbose_name="Allowed Routes",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "ordering": ("end_date",),
            },
        ),
        migrations.CreateModel(
            name="ApiLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="The IP address of the request sender.",
                        null=True,
                        unpack_ipv4=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True,
                        help_text="The API request path (e.g., '/api/orders/123/').",
                        max_length=2048,
                        null=True,
                        verbose_name="Request Path",
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (200, "OK"),
                            (201, "Created"),
                            (204, "No Content"),
                            (400, "Bad Request"),
                            (401, "Unauthorized"),
                            (403, "Forbidden"),
                            (404, "Not Found"),
                            (500, "Internal Server Error"),
                            (502, "Bad Gateway"),
                            (503, "Service Unavailable"),
                        ],
                        help_text="HTTP status code returned by the API call.",
                        null=True,
                        verbose_name="Status Code",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="System-generated message describing the request result.",
                        null=True,
                        verbose_name="Message",
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        help_text="The API key used to make this call.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_logs",
                        related_query_name="api_log",
                        to="gc_users.apikey",
                        verbose_name="API Key",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Log Entry",
                "verbose_name_plural": "API Log Entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="gc_users_ap_created_f67568_idx"
                    ),
                    models.Index(
                        fields=["api_key"], name="gc_users_ap_api_key_5b0b4e_idx"
                    ),
                    models.Index(
                        fields=["status_code"], name="gc_users_ap_status__e8a804_idx"
                    ),
                ],
            },
        ),
    ]
