# Generated by Django 6.0 on 2025-12-06 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gc_users', '0004_historicalapikey_historicalorganization_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='routes',
        ),
        migrations.RemoveIndex(
            model_name='apilog',
            name='gc_users_ap_created_f67568_idx',
        ),
        migrations.RemoveIndex(
            model_name='apilog',
            name='gc_users_ap_api_key_5b0b4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='apilog',
            name='gc_users_ap_status__e8a804_idx',
        ),
        migrations.RemoveField(
            model_name='historicalapikey',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalapikey',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='apilog',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='apilog',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ApiRoute',
        ),
        migrations.DeleteModel(
            name='HistoricalApiKey',
        ),
        migrations.DeleteModel(
            name='ApiKey',
        ),
        migrations.DeleteModel(
            name='ApiLog',
        ),
    ]
