# Generated by Django 6.0 on 2025-12-07 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gc_users', '0007_organization_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who owns this organization.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='name',
            field=models.CharField(db_index=True, help_text='The name of this organization.', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='The name of this organization.', max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
