# Generated by Django 6.0 on 2025-12-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gc_users', '0008_historicalorganization_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcuser',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User-specific preferences and UI state.'),
        ),
    ]
