"""
Django settings for gc_core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-!^j56zyvtu4=c6q09t#^4%l$7)o0vb^il3z2^wmi465oda+0!s"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Priority Apps
    "gc_dashboard",
    # Third-Party Apps
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "unfold.contrib.import_export",
    "unfold.contrib.simple_history",
    "simple_history",
    # Django Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # First-Party Apps
    "gc_users",
    "gc_core",
    "gc_collections",
    "gc_definitions",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = "gc_core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "gc_core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTH_USER_MODEL = "gc_users.GcUser"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

# Set server time to Eastern US (New York)
TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django Unfold configuration
UNFOLD = {
    "SITE_TITLE": "Galway Clarke",
    "SITE_HEADER": "Galway Clarke",
    "COLORS": {
        "primary": {
            "50": "#ecfdf3",
            "100": "#d1fae4",
            "200": "#a7f3c8",
            "300": "#6ee7a0",
            "400": "#34d57c",
            "500": "#16c066",
            "600": "#109256",
            "700": "#0b6c45",
            "800": "#0a5a3a",
            "900": "#094c31",
            "950": "#042c1c",
        },
    },
    "STYLES": [
        "/static/gc_dashboard/dashboard.css",
    ],
    "SIDEBAR": {
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Art and Architecture Terminiology",
                "items": [
                    {
                        "title": "Subjects",
                        "icon": "category",
                        "link": "/admin/gc_collections/aatsubject/",
                    },
                    {
                        "title": "Subject Contributors",
                        "icon": "group_add",
                        "link": "/admin/gc_collections/aatsubjectcontributor/",
                    },
                    {
                        "title": "Subject Sources",
                        "icon": "source",
                        "link": "/admin/gc_collections/aatsubjectsource/",
                    },
                    {
                        "title": "Associative Relationships",
                        "icon": "link",
                        "link": "/admin/gc_collections/aatassociativerelationship/",
                    },
                    {
                        "title": "Terms",
                        "icon": "label",
                        "link": "/admin/gc_collections/aatterm/",
                    },
                    {
                        "title": "Term Contributors",
                        "icon": "diversity_3",
                        "link": "/admin/gc_collections/aattermcontributor/",
                    },
                    {
                        "title": "Term Sources",
                        "icon": "menu_book",
                        "link": "/admin/gc_collections/aattermsource/",
                    },
                    {
                        "title": "Notes",
                        "icon": "note",
                        "link": "/admin/gc_collections/aatnote/",
                    },
                    {
                        "title": "Note Contributors",
                        "icon": "record_voice_over",
                        "link": "/admin/gc_collections/aatnotecontributor/",
                    },
                    {
                        "title": "Note Sources",
                        "icon": "library_books",
                        "link": "/admin/gc_collections/aatnotesource/",
                    },
                ],
            },
            {
                "title": "API",
                "items": [
                    {
                        "title": "API Keys",
                        "icon": "key",
                        "link": "/admin/gc_users/apikey/",
                    },
                    {
                        "title": "API Routes",
                        "icon": "route",
                        "link": "/admin/gc_users/apiroute/",
                    },
                    {
                        "title": "API Logs",
                        "icon": "list_alt",
                        "link": "/admin/gc_users/apilog/",
                    },
                    {
                        "title": "API Docs",
                        "icon": "api",
                        "link": "/api/docs",
                    },
                ],
            },
            {
                "title": "Users and Groups",
                "items": [
                    {
                        "title": "Organizations",
                        "icon": "corporate_fare",
                        "link": "/admin/gc_users/organization/",
                    },
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": "/admin/gc_users/gcuser/",
                    },
                    {
                        "title": "Groups",
                        "icon": "group",
                        "link": "/admin/auth/group/",
                    },
                ],
            },
        ],
    },
}
