# Generated by Django 6.0 on 2025-12-13 22:59

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gc_geography', '0001_initial'),
        ('gc_users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('address_one', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1')),
                ('address_two', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('primary', models.BooleanField(default=False, verbose_name='Primary Contact')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this individual.', null=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('location_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_individuals_city', to='gc_geography.city', verbose_name='City')),
                ('location_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_individuals_county', to='gc_geography.county', verbose_name='County')),
                ('location_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_individuals_state', to='gc_geography.state', verbose_name='State/Region')),
                ('location_zip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_individuals_zip', to='gc_geography.zipcode', verbose_name='Zip Code')),
            ],
            options={
                'verbose_name': 'Individual',
                'verbose_name_plural': 'Individuals',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('team', models.ForeignKey(help_text='Team that owns this industry definition.', on_delete=django.db.models.deletion.CASCADE, related_name='crm_industries', to='gc_users.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address_one', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1')),
                ('address_two', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Activity')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this organization.', null=True, verbose_name='Notes')),
                ('account', models.ForeignKey(help_text='Owning team within Galway Clarke.', on_delete=django.db.models.deletion.CASCADE, related_name='crm_organizations', to='gc_users.team', verbose_name='Team')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='gc_crm.industry', verbose_name='Industry')),
                ('location_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_organizations_city', to='gc_geography.city', verbose_name='City')),
                ('location_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_organizations_county', to='gc_geography.county', verbose_name='County')),
                ('location_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_organizations_state', to='gc_geography.state', verbose_name='State/Region')),
                ('location_zip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_organizations_zip', to='gc_geography.zipcode', verbose_name='Zip Code')),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_organizations', to='gc_crm.individual', verbose_name='Primary Contact')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='individual',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_crm.organization', verbose_name='Organization'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(help_text='Lifecycle status (active, pending, churn risk, etc.).', max_length=80, verbose_name='Name')),
                ('color', models.CharField(choices=[('slate', 'Slate'), ('gray', 'Gray'), ('zinc', 'Zinc'), ('neutral', 'Neutral'), ('stone', 'Stone'), ('red', 'Red'), ('orange', 'Orange'), ('amber', 'Amber'), ('yellow', 'Yellow'), ('lime', 'Lime'), ('green', 'Green'), ('emerald', 'Emerald'), ('teal', 'Teal'), ('cyan', 'Cyan'), ('sky', 'Sky'), ('blue', 'Blue'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('purple', 'Purple'), ('fuchsia', 'Fuchsia'), ('pink', 'Pink'), ('rose', 'Rose')], default='gray', help_text='Optional hex or token to style this status.', max_length=20, verbose_name='Color')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('team', models.ForeignKey(help_text='Team that owns this status definition.', on_delete=django.db.models.deletion.CASCADE, related_name='crm_statuses', to='gc_users.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Lifecycle status for this organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='gc_crm.status', verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='HistoricalOrganization',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Last Updated')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address_one', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1')),
                ('address_two', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Activity')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this organization.', null=True, verbose_name='Notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, help_text='Owning team within Galway Clarke.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gc_users.team', verbose_name='Team')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location_city', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gc_geography.city', verbose_name='City')),
                ('location_county', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gc_geography.county', verbose_name='County')),
                ('location_state', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gc_geography.state', verbose_name='State/Region')),
                ('location_zip', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gc_geography.zipcode', verbose_name='Zip Code')),
                ('primary_contact', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gc_crm.individual', verbose_name='Primary Contact')),
                ('industry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gc_crm.industry', verbose_name='Industry')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, help_text='Lifecycle status for this organization.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gc_crm.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'historical Organization',
                'verbose_name_plural': 'historical Organizations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('color', models.CharField(blank=True, help_text='Optional hex or token to style this tag.', max_length=20, null=True, verbose_name='Color')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('team', models.ForeignKey(help_text='Team that owns this tag.', on_delete=django.db.models.deletion.CASCADE, related_name='crm_tags', to='gc_users.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Labels applied to this organization.', related_name='organizations', to='gc_crm.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='individual',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='individuals', to='gc_crm.tag', verbose_name='Tags'),
        ),
    ]
