# Generated by Django 6.0 on 2025-12-14 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gc_crm', '0001_initial'),
        ('gc_geography', '0001_initial'),
        ('gc_users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='location_city',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gc_geography.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='location_county',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gc_geography.county', verbose_name='County'),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='location_state',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gc_geography.state', verbose_name='State/Region'),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='location_zip',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gc_geography.zipcode', verbose_name='Zip Code'),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='team',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Owning team within Galway Clarke.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gc_users.team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='individual',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='individual',
            name='location_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_individuals_city', to='gc_geography.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='individual',
            name='location_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_individuals_county', to='gc_geography.county', verbose_name='County'),
        ),
        migrations.AddField(
            model_name='individual',
            name='location_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_individuals_state', to='gc_geography.state', verbose_name='State/Region'),
        ),
        migrations.AddField(
            model_name='individual',
            name='location_zip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_individuals_zip', to='gc_geography.zipcode', verbose_name='Zip Code'),
        ),
        migrations.AddField(
            model_name='individual',
            name='team',
            field=models.ForeignKey(help_text='Owning team within Galway Clarke.', on_delete=django.db.models.deletion.CASCADE, related_name='crm_individuals', to='gc_users.team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='primary_contact',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gc_crm.individual', verbose_name='Primary Contact'),
        ),
        migrations.AddField(
            model_name='industry',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='industry',
            name='team',
            field=models.ForeignKey(help_text='Team that owns this industry definition.', on_delete=django.db.models.deletion.CASCADE, related_name='crm_industries', to='gc_users.team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='industry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gc_crm.industry', verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='gc_crm.industry', verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='organization',
            name='location_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_organizations_city', to='gc_geography.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='organization',
            name='location_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_organizations_county', to='gc_geography.county', verbose_name='County'),
        ),
        migrations.AddField(
            model_name='organization',
            name='location_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_organizations_state', to='gc_geography.state', verbose_name='State/Region'),
        ),
        migrations.AddField(
            model_name='organization',
            name='location_zip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_organizations_zip', to='gc_geography.zipcode', verbose_name='Zip Code'),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_organizations', to='gc_crm.individual', verbose_name='Primary Contact'),
        ),
        migrations.AddField(
            model_name='organization',
            name='team',
            field=models.ForeignKey(help_text='Owning team within Galway Clarke.', on_delete=django.db.models.deletion.CASCADE, related_name='crm_organizations', to='gc_users.team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='individual',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_crm.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='status',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='status',
            name='team',
            field=models.ForeignKey(help_text='Team that owns this status definition.', on_delete=django.db.models.deletion.CASCADE, related_name='crm_statuses', to='gc_users.team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Lifecycle status for this organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='gc_crm.status', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Lifecycle status for this organization.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gc_crm.status', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='tag',
            name='team',
            field=models.ForeignKey(help_text='Team that owns this tag.', on_delete=django.db.models.deletion.CASCADE, related_name='crm_tags', to='gc_users.team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Labels applied to this organization.', related_name='organizations', to='gc_crm.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='individual',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='individuals', to='gc_crm.tag', verbose_name='Tags'),
        ),
    ]
