# Generated by Django 6.0 on 2025-12-13 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(max_length=255, verbose_name='State')),
                ('abbreviation', models.CharField(blank=True, help_text='Two-letter state abbreviation.', max_length=2, null=True, verbose_name='Abbreviation')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(max_length=255, verbose_name='County')),
                ('fips_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='FIPS Code')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_geography.state', verbose_name='State')),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
                'ordering': ('state', 'name'),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(max_length=255, verbose_name='City')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_geography.county', verbose_name='County')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_geography.state', verbose_name='State')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ('state', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('zip_code_five_digit', models.CharField(max_length=5, verbose_name='ZIP Code (5 Digit)')),
                ('zip_code_nine_digit', models.CharField(blank=True, max_length=255, null=True, verbose_name='ZIP Code (9 Digit)')),
                ('population', models.IntegerField(blank=True, default=0, null=True, verbose_name='Population')),
                ('density', models.FloatField(blank=True, help_text='Population density per square mile.', null=True, verbose_name='Density')),
                ('cities', models.ManyToManyField(blank=True, related_name='zip_codes', to='gc_geography.city', verbose_name='Cities')),
                ('counties', models.ManyToManyField(blank=True, related_name='zip_codes', to='gc_geography.county', verbose_name='Counties')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('states', models.ManyToManyField(blank=True, related_name='zip_codes', to='gc_geography.state', verbose_name='States')),
            ],
            options={
                'verbose_name': 'ZIP Code',
                'verbose_name_plural': 'ZIP Codes',
                'ordering': ('zip_code_five_digit',),
            },
        ),
    ]
