# Generated by Django 5.2.8 on 2025-12-01 05:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AatNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('note_text', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'AAT Note',
                'verbose_name_plural': 'AAT Notes',
            },
        ),
        migrations.CreateModel(
            name='AatNoteContributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('contributor_id', models.CharField(help_text='Contributor ID for descriptive note', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='gc_definitions.aatnote')),
            ],
            options={
                'verbose_name': 'AAT Note Contributor',
                'verbose_name_plural': 'AAT Note Contributors',
            },
        ),
        migrations.CreateModel(
            name='AatNoteSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('source_id', models.CharField(help_text='Source reference for note text', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='gc_definitions.aatnote')),
            ],
            options={
                'verbose_name': 'AAT Note Source',
                'verbose_name_plural': 'AAT Note Sources',
            },
        ),
        migrations.CreateModel(
            name='AatSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('aat_id', models.CharField(help_text='Getty AAT Subject_ID', max_length=32, unique=True)),
                ('record_type', models.CharField(blank=True, help_text="Record_Type field (e.g., 'Concept')", max_length=50, null=True)),
                ('merged_status', models.CharField(blank=True, help_text='Merged_Status field', max_length=50, null=True)),
                ('sort_order', models.IntegerField(blank=True, help_text='Sort_Order', null=True)),
                ('parent_aat_id', models.CharField(blank=True, help_text='Preferred Parent_Subject_ID', max_length=32, null=True)),
                ('parent_string', models.TextField(blank=True, help_text='Parent_String listing hierarchy ancestors', null=True)),
                ('parent_relationship_type', models.CharField(blank=True, help_text="Hier_Rel_Type (e.g., 'Genus/Species-BTG')", max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'AAT Subject',
                'verbose_name_plural': 'AAT Subjects',
            },
        ),
        migrations.AddField(
            model_name='aatnote',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='gc_definitions.aatsubject'),
        ),
        migrations.CreateModel(
            name='AatAssociativeRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('relationship_type', models.CharField(help_text="Relationship_Type (e.g., 'distinguished from')", max_length=100)),
                ('related_aat_id', models.CharField(help_text='VP_Subject_ID for the related concept', max_length=32)),
                ('historic_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associative_relationships', to='gc_definitions.aatsubject')),
            ],
            options={
                'verbose_name': 'AAT Associative Relationship',
                'verbose_name_plural': 'AAT Associative Relationships',
            },
        ),
        migrations.CreateModel(
            name='AatSubjectContributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('contributor_id', models.CharField(help_text='Contributor_id inside <Subject_Contributor>', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_contributors', to='gc_definitions.aatsubject')),
            ],
            options={
                'verbose_name': 'AAT Subject Contributor',
                'verbose_name_plural': 'AAT Subject Contributors',
            },
        ),
        migrations.CreateModel(
            name='AatSubjectSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('source_id', models.CharField(help_text='Source_ID inside <Subject_Source>', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_sources', to='gc_definitions.aatsubject')),
            ],
            options={
                'verbose_name': 'AAT Subject Source',
                'verbose_name_plural': 'AAT Subject Sources',
            },
        ),
        migrations.CreateModel(
            name='AatTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('term_id', models.CharField(help_text='Term_ID inside <Preferred_Term> or <Non-Preferred_Term>', max_length=32)),
                ('term_text', models.CharField(help_text='Primary term text', max_length=500)),
                ('display_name', models.CharField(blank=True, max_length=500, null=True)),
                ('historic_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('vernacular', models.CharField(blank=True, max_length=50, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('term_type', models.CharField(blank=True, help_text='Descriptor, Alternate Descriptor, Used For Term, etc.', max_length=100, null=True)),
                ('part_of_speech', models.CharField(blank=True, max_length=100, null=True)),
                ('qualifier', models.CharField(blank=True, max_length=250, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='gc_definitions.aatsubject')),
            ],
            options={
                'verbose_name': 'AAT Term',
                'verbose_name_plural': 'AAT Terms',
            },
        ),
        migrations.CreateModel(
            name='AatTermContributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('contributor_id', models.CharField(help_text='Contributor_id for a term', max_length=100)),
                ('preferred_flag', models.CharField(blank=True, help_text='Preferred, Non Preferred, etc.', max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='gc_definitions.aatterm')),
            ],
            options={
                'verbose_name': 'AAT Term Contributor',
                'verbose_name_plural': 'AAT Term Contributors',
            },
        ),
        migrations.CreateModel(
            name='AatTermSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('source_id', models.CharField(help_text='Source_ID from <Term_Source>', max_length=255)),
                ('page', models.CharField(blank=True, help_text='Page or extra locator info', max_length=100, null=True)),
                ('preferred_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='gc_definitions.aatterm')),
            ],
            options={
                'verbose_name': 'AAT Term Source',
                'verbose_name_plural': 'AAT Term Sources',
            },
        ),
        migrations.CreateModel(
            name='IsoLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(help_text='Offical name of the language', max_length=255)),
                ('iso_set_639_1_code', models.CharField(blank=True, help_text='ISO 639-1 code for the language', max_length=3, null=True, verbose_name='ISO 639-1 Code')),
                ('iso_set_639_2_code', models.CharField(blank=True, help_text='ISO 639-2 code for the language', max_length=3, null=True, verbose_name='ISO 639-2 Code')),
                ('iso_set_639_3_code', models.CharField(blank=True, help_text='ISO 639-3 code for the language', max_length=3, null=True, verbose_name='ISO 639-3 Code')),
                ('iso_set_639_5_code', models.CharField(blank=True, help_text='ISO 639-5 code for the language', max_length=3, null=True, verbose_name='ISO 639-5 Code')),
                ('getty_language_code', models.CharField(blank=True, help_text='Getty language code for the language', max_length=20, null=True, verbose_name='Getty Language Code')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'ISO Language',
                'verbose_name_plural': 'ISO Languages',
            },
        ),
        migrations.AddField(
            model_name='aatterm',
            name='language_code',
            field=models.ForeignKey(blank=True, help_text="Parsed from language field (e.g., '70051/English')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_definitions.isolanguage'),
        ),
        migrations.AddField(
            model_name='aatnote',
            name='note_language',
            field=models.ForeignKey(blank=True, help_text="Parsed from language field (e.g., '70051/English')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_definitions.isolanguage'),
        ),
        migrations.CreateModel(
            name='IsoLanguageScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(help_text='ISO Language Scope Name', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'ISO Language Scope',
                'verbose_name_plural': 'ISO Language Scopes',
            },
        ),
        migrations.AddField(
            model_name='isolanguage',
            name='iso_language_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languages', to='gc_definitions.isolanguagescope', verbose_name='ISO Language Scope'),
        ),
        migrations.CreateModel(
            name='IsoLanguageType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(help_text='ISO Language Type Name', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'ISO Language Type',
                'verbose_name_plural': 'ISO Language Types',
            },
        ),
        migrations.AddField(
            model_name='isolanguage',
            name='iso_language_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languages', to='gc_definitions.isolanguagetype', verbose_name='ISO Language Type'),
        ),
    ]
