# Generated by Django 5.2.8 on 2025-11-30 23:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gc_definitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IsoLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(help_text='Offical name of the language', max_length=255)),
                ('iso_set_639_1_code', models.CharField(blank=True, help_text='ISO 639-1 code for the language', max_length=3, null=True)),
                ('iso_set_639_2_code', models.CharField(blank=True, help_text='ISO 639-2 code for the language', max_length=3, null=True)),
                ('iso_set_639_3_code', models.CharField(blank=True, help_text='ISO 639-3 code for the language', max_length=3, null=True)),
                ('iso_set_639_5_code', models.CharField(blank=True, help_text='ISO 639-5 code for the language', max_length=3, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'ISO Language',
                'verbose_name_plural': 'ISO Languages',
            },
        ),
        migrations.CreateModel(
            name='IsoLanguageScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(help_text='ISO Language Scope Name', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'ISO Language Scope',
                'verbose_name_plural': 'ISO Language Scopes',
            },
        ),
        migrations.CreateModel(
            name='IsoLanguageType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(help_text='ISO Language Type Name', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'ISO Language Type',
                'verbose_name_plural': 'ISO Language Types',
            },
        ),
    ]
