# Generated by Django 5.2.8 on 2025-12-01 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gc_definitions", "0002_isolanguage_isolanguagescope_isolanguagetype"),
    ]

    operations = [
        migrations.AddField(
            model_name="isolanguage",
            name="iso_language_scope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="languages",
                to="gc_definitions.isolanguagescope",
            ),
        ),
        migrations.AddField(
            model_name="isolanguage",
            name="iso_language_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="languages",
                to="gc_definitions.isolanguagetype",
            ),
        ),
    ]
