# Generated by Django 5.2.8 on 2025-12-01 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gc_definitions', '0003_isolanguage_iso_language_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='isolanguage',
            name='getty_language_code',
            field=models.CharField(blank=True, help_text='Getty language code for the language', max_length=20, null=True, verbose_name='Getty Language Code'),
        ),
        migrations.AlterField(
            model_name='isolanguage',
            name='iso_language_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languages', to='gc_definitions.isolanguagescope', verbose_name='ISO Language Scope'),
        ),
        migrations.AlterField(
            model_name='isolanguage',
            name='iso_language_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languages', to='gc_definitions.isolanguagetype', verbose_name='ISO Language Type'),
        ),
        migrations.AlterField(
            model_name='isolanguage',
            name='iso_set_639_1_code',
            field=models.CharField(blank=True, help_text='ISO 639-1 code for the language', max_length=3, null=True, verbose_name='ISO 639-1 Code'),
        ),
        migrations.AlterField(
            model_name='isolanguage',
            name='iso_set_639_2_code',
            field=models.CharField(blank=True, help_text='ISO 639-2 code for the language', max_length=3, null=True, verbose_name='ISO 639-2 Code'),
        ),
        migrations.AlterField(
            model_name='isolanguage',
            name='iso_set_639_3_code',
            field=models.CharField(blank=True, help_text='ISO 639-3 code for the language', max_length=3, null=True, verbose_name='ISO 639-3 Code'),
        ),
        migrations.AlterField(
            model_name='isolanguage',
            name='iso_set_639_5_code',
            field=models.CharField(blank=True, help_text='ISO 639-5 code for the language', max_length=3, null=True, verbose_name='ISO 639-5 Code'),
        ),
    ]
