# Generated by Django 5.2.8 on 2025-12-01 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gc_definitions', '0004_isolanguage_getty_language_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aatnote',
            name='note_language',
        ),
        migrations.RemoveField(
            model_name='aatterm',
            name='language_code',
        ),
    ]
