# Generated by Django 6.0 on 2025-12-13 20:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AatAssociativeRelationshipType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(help_text="Relationship_Type value (e.g., 'distinguished from')", max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'AAT Associative Relationship Type',
                'verbose_name_plural': 'AAT Associative Relationship Types',
            },
        ),
        migrations.CreateModel(
            name='AatNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('note_text', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'AAT Note',
                'verbose_name_plural': 'AAT Notes',
            },
        ),
        migrations.CreateModel(
            name='AatNoteContributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('contributor_id', models.CharField(help_text='Contributor ID for descriptive note', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='gc_reference.aatnote')),
            ],
            options={
                'verbose_name': 'AAT Note Contributor',
                'verbose_name_plural': 'AAT Note Contributors',
            },
        ),
        migrations.CreateModel(
            name='AatNoteSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('source_id', models.CharField(help_text='Source reference for note text', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='gc_reference.aatnote')),
            ],
            options={
                'verbose_name': 'AAT Note Source',
                'verbose_name_plural': 'AAT Note Sources',
            },
        ),
        migrations.CreateModel(
            name='AatParentRelationshipType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(help_text="Parent relationship type (e.g., 'Genus/Species-BTG')", max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'AAT Parent Relationship Type',
                'verbose_name_plural': 'AAT Parent Relationship Types',
            },
        ),
        migrations.CreateModel(
            name='AatSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('aat_id', models.CharField(help_text='Getty AAT Subject_ID', max_length=32, unique=True, verbose_name='AAT Subject ID')),
                ('merged_status', models.CharField(blank=True, help_text='Merged_Status Field', max_length=50, null=True, verbose_name='Merged Status')),
                ('sort_order', models.IntegerField(blank=True, help_text='Sort_Order', null=True, verbose_name='Sort Order')),
                ('parent_string', models.TextField(blank=True, help_text='Parent_String Listing Hierarchy Ancestors', null=True, verbose_name='Parent String')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent', models.ForeignKey(blank=True, help_text='Preferred parent subject', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='gc_reference.aatsubject', verbose_name='Parent Subject')),
                ('parent_relationship_type', models.ForeignKey(blank=True, help_text="Hier_Rel_Type (e.g., 'Genus/Species-BTG')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.aatparentrelationshiptype', verbose_name='Parent Relationship Type')),
            ],
            options={
                'verbose_name': 'AAT Subject',
                'verbose_name_plural': 'AAT Subjects',
            },
        ),
        migrations.AddField(
            model_name='aatnote',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='gc_reference.aatsubject'),
        ),
        migrations.CreateModel(
            name='AatAssociativeRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('historic_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('relationship_type', models.ForeignKey(blank=True, help_text="Relationship_Type (e.g., 'distinguished from')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associative_relationships', to='gc_reference.aatassociativerelationshiptype')),
                ('related_subject', models.ForeignKey(help_text='VP_Subject_ID for the related concept', on_delete=django.db.models.deletion.CASCADE, related_name='associative_relationships_to', to='gc_reference.aatsubject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associative_relationships', to='gc_reference.aatsubject')),
            ],
            options={
                'verbose_name': 'AAT Associative Relationship',
                'verbose_name_plural': 'AAT Associative Relationships',
            },
        ),
        migrations.CreateModel(
            name='AatSubjectContributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('contributor_id', models.CharField(help_text='Contributor_id inside <Subject_Contributor>', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_contributors', to='gc_reference.aatsubject')),
            ],
            options={
                'verbose_name': 'AAT Subject Contributor',
                'verbose_name_plural': 'AAT Subject Contributors',
            },
        ),
        migrations.CreateModel(
            name='AatSubjectRecordType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(help_text='Record_Type value (e.g., Concept)', max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'AAT Subject Record Type',
                'verbose_name_plural': 'AAT Subject Record Types',
            },
        ),
        migrations.AddField(
            model_name='aatsubject',
            name='record_type',
            field=models.ForeignKey(blank=True, help_text="Record_Type Field (e.g., 'Concept')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.aatsubjectrecordtype', verbose_name='Record Type'),
        ),
        migrations.CreateModel(
            name='AatSubjectSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('source_id', models.CharField(help_text='Source_ID inside <Subject_Source>', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_sources', to='gc_reference.aatsubject')),
            ],
            options={
                'verbose_name': 'AAT Subject Source',
                'verbose_name_plural': 'AAT Subject Sources',
            },
        ),
        migrations.CreateModel(
            name='AatTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('term_id', models.CharField(help_text='Term_ID inside <Preferred_Term> or <Non-Preferred_Term>', max_length=32)),
                ('term_text', models.CharField(help_text='Primary term text', max_length=500)),
                ('display_name', models.CharField(blank=True, max_length=500, null=True)),
                ('historic_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('vernacular', models.CharField(blank=True, max_length=50, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('term_type', models.CharField(blank=True, help_text='Descriptor, Alternate Descriptor, Used For Term, etc.', max_length=100, null=True)),
                ('part_of_speech', models.CharField(blank=True, max_length=100, null=True)),
                ('qualifier', models.CharField(blank=True, max_length=250, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='gc_reference.aatsubject')),
            ],
            options={
                'verbose_name': 'AAT Term',
                'verbose_name_plural': 'AAT Terms',
            },
        ),
        migrations.CreateModel(
            name='AatTermContributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('contributor_id', models.CharField(help_text='Contributor_id for a term', max_length=100)),
                ('preferred_flag', models.CharField(blank=True, help_text='Preferred, Non Preferred, etc.', max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='gc_reference.aatterm')),
            ],
            options={
                'verbose_name': 'AAT Term Contributor',
                'verbose_name_plural': 'AAT Term Contributors',
            },
        ),
        migrations.CreateModel(
            name='AatTermSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('source_id', models.CharField(help_text='Source_ID from <Term_Source>', max_length=255)),
                ('page', models.CharField(blank=True, help_text='Page or extra locator info', max_length=100, null=True)),
                ('preferred_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='gc_reference.aatterm')),
            ],
            options={
                'verbose_name': 'AAT Term Source',
                'verbose_name_plural': 'AAT Term Sources',
            },
        ),
        migrations.CreateModel(
            name='IsoLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(help_text='Offical name of the language', max_length=255)),
                ('iso_set_639_1_code', models.CharField(blank=True, help_text='ISO 639-1 code for the language', max_length=3, null=True, verbose_name='ISO 639-1 Code')),
                ('iso_set_639_2_code', models.CharField(blank=True, help_text='ISO 639-2 code for the language', max_length=3, null=True, verbose_name='ISO 639-2 Code')),
                ('iso_set_639_3_code', models.CharField(blank=True, help_text='ISO 639-3 code for the language', max_length=3, null=True, verbose_name='ISO 639-3 Code')),
                ('iso_set_639_5_code', models.CharField(blank=True, help_text='ISO 639-5 code for the language', max_length=3, null=True, verbose_name='ISO 639-5 Code')),
                ('getty_language_code', models.CharField(blank=True, help_text='Getty language code for the language', max_length=20, null=True, verbose_name='Getty Language Code')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'ISO Language',
                'verbose_name_plural': 'ISO Languages',
            },
        ),
        migrations.AddField(
            model_name='aatterm',
            name='language_code',
            field=models.ForeignKey(blank=True, help_text="Parsed from language field (e.g., '70051/English')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.isolanguage'),
        ),
        migrations.AddField(
            model_name='aatnote',
            name='note_language',
            field=models.ForeignKey(blank=True, help_text="Parsed from language field (e.g., '70051/English')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.isolanguage'),
        ),
        migrations.CreateModel(
            name='IsoLanguageScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(help_text='ISO Language Scope Name', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'ISO Language Scope',
                'verbose_name_plural': 'ISO Language Scopes',
            },
        ),
        migrations.AddField(
            model_name='isolanguage',
            name='iso_language_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languages', to='gc_reference.isolanguagescope', verbose_name='ISO Language Scope'),
        ),
        migrations.CreateModel(
            name='IsoLanguageType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(help_text='ISO Language Type Name', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'ISO Language Type',
                'verbose_name_plural': 'ISO Language Types',
            },
        ),
        migrations.AddField(
            model_name='isolanguage',
            name='iso_language_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languages', to='gc_reference.isolanguagetype', verbose_name='ISO Language Type'),
        ),
        migrations.CreateModel(
            name='UlanAssociativeRelationshipType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(help_text='Relationship type label for ULAN associative relationships', max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'ULAN Associative Relationship Type',
                'verbose_name_plural': 'ULAN Associative Relationship Types',
            },
        ),
        migrations.CreateModel(
            name='UlanNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('note_text', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('note_language', models.ForeignKey(blank=True, help_text='Parsed from <Note_Language>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.isolanguage')),
            ],
            options={
                'verbose_name': 'ULAN Note',
                'verbose_name_plural': 'ULAN Notes',
            },
        ),
        migrations.CreateModel(
            name='UlanNoteContributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('contributor_id', models.CharField(help_text='Contributor_id inside <Note_Contributor>', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='gc_reference.ulannote')),
            ],
            options={
                'verbose_name': 'ULAN Note Contributor',
                'verbose_name_plural': 'ULAN Note Contributors',
            },
        ),
        migrations.CreateModel(
            name='UlanNoteSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('source_id', models.CharField(help_text='Source_ID inside <Note_Source>', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='gc_reference.ulannote')),
            ],
            options={
                'verbose_name': 'ULAN Note Source',
                'verbose_name_plural': 'ULAN Note Sources',
            },
        ),
        migrations.CreateModel(
            name='UlanParentRelationshipType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(help_text='Hier_Rel_Type (e.g. Instance-BTI)', max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'ULAN Parent Relationship Type',
                'verbose_name_plural': 'ULAN Parent Relationship Types',
            },
        ),
        migrations.CreateModel(
            name='UlanPartOfSpeech',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(help_text='Part of Speech value for ULAN terms', max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'ULAN Part of Speech',
                'verbose_name_plural': 'ULAN Parts of Speech',
            },
        ),
        migrations.CreateModel(
            name='UlanSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('ulan_id', models.CharField(help_text='Getty ULAN Subject_ID', max_length=32, unique=True)),
                ('merged_status', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_string', models.TextField(blank=True, help_text='Parent_String ancestry chain', null=True)),
                ('parent_historic_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent_Subject_ID for hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='gc_reference.ulansubject')),
                ('parent_relationship_type', models.ForeignKey(blank=True, help_text='Hier_Rel_Type (e.g. Instance-BTI)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.ulanparentrelationshiptype')),
            ],
            options={
                'verbose_name': 'ULAN Subject',
                'verbose_name_plural': 'ULAN Subjects',
            },
        ),
        migrations.CreateModel(
            name='UlanRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('role_id', models.CharField(max_length=100)),
                ('historic_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='gc_reference.ulansubject')),
            ],
            options={
                'verbose_name': 'ULAN Role',
                'verbose_name_plural': 'ULAN Roles',
            },
        ),
        migrations.AddField(
            model_name='ulannote',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='gc_reference.ulansubject'),
        ),
        migrations.CreateModel(
            name='UlanNationality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('nationality_code', models.CharField(help_text='e.g., 901600/French', max_length=100)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nationalities', to='gc_reference.ulansubject')),
            ],
            options={
                'verbose_name': 'ULAN Nationality',
                'verbose_name_plural': 'ULAN Nationalities',
            },
        ),
        migrations.CreateModel(
            name='UlanBiography',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('biography_id', models.CharField(max_length=50)),
                ('biography_text', models.TextField()),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_tgn_id', models.CharField(blank=True, max_length=32, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=50, null=True)),
                ('death_place', models.CharField(blank=True, max_length=255, null=True)),
                ('death_tgn_id', models.CharField(blank=True, max_length=32, null=True)),
                ('death_date', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('contributor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biographies', to='gc_reference.ulansubject')),
            ],
            options={
                'verbose_name': 'ULAN Biography',
                'verbose_name_plural': 'ULAN Biographies',
            },
        ),
        migrations.CreateModel(
            name='UlanAssociativeRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('historic_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('display_date', models.CharField(blank=True, help_text='Display_Date inside <AR_Date>', max_length=255, null=True)),
                ('start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('relationship_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associative_relationships', to='gc_reference.ulanassociativerelationshiptype')),
                ('related_subject', models.ForeignKey(help_text='Related ULAN subject', on_delete=django.db.models.deletion.CASCADE, related_name='associative_relationships_to', to='gc_reference.ulansubject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associative_relationships', to='gc_reference.ulansubject')),
            ],
            options={
                'verbose_name': 'ULAN Associative Relationship',
                'verbose_name_plural': 'ULAN Associative Relationships',
            },
        ),
        migrations.CreateModel(
            name='UlanSubjectContributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('contributor_id', models.CharField(help_text='Contributor_id within <Subject_Contributor>', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_contributors', to='gc_reference.ulansubject')),
            ],
            options={
                'verbose_name': 'ULAN Subject Contributor',
                'verbose_name_plural': 'ULAN Subject Contributors',
            },
        ),
        migrations.CreateModel(
            name='UlanSubjectRecordType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(help_text='Record_Type (e.g., Person, Corporate Body, Family, Group)', max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'ULAN Subject Record Type',
                'verbose_name_plural': 'ULAN Subject Record Types',
            },
        ),
        migrations.AddField(
            model_name='ulansubject',
            name='record_type',
            field=models.ForeignKey(blank=True, help_text='Record_Type (e.g., Person, Corporate Body, Family, Group)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.ulansubjectrecordtype'),
        ),
        migrations.CreateModel(
            name='UlanSubjectSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('source_id', models.CharField(help_text='Source_ID inside <Subject_Source>', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_sources', to='gc_reference.ulansubject')),
            ],
            options={
                'verbose_name': 'ULAN Subject Source',
                'verbose_name_plural': 'ULAN Subject Sources',
            },
        ),
        migrations.CreateModel(
            name='UlanTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('term_id', models.CharField(max_length=32)),
                ('term_text', models.CharField(max_length=500)),
                ('display_name', models.CharField(blank=True, max_length=500, null=True)),
                ('historic_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('vernacular', models.CharField(blank=True, max_length=50, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('qualifier', models.CharField(blank=True, max_length=250, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('language_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.isolanguage')),
                ('part_of_speech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.ulanpartofspeech')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='gc_reference.ulansubject')),
            ],
            options={
                'verbose_name': 'ULAN Term',
                'verbose_name_plural': 'ULAN Terms',
            },
        ),
        migrations.CreateModel(
            name='UlanTermContributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('contributor_id', models.CharField(max_length=100)),
                ('preferred_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='gc_reference.ulanterm')),
            ],
            options={
                'verbose_name': 'ULAN Term Contributor',
                'verbose_name_plural': 'ULAN Term Contributors',
            },
        ),
        migrations.CreateModel(
            name='UlanTermSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('source_id', models.CharField(max_length=255)),
                ('page', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='gc_reference.ulanterm')),
            ],
            options={
                'verbose_name': 'ULAN Term Source',
                'verbose_name_plural': 'ULAN Term Sources',
            },
        ),
        migrations.CreateModel(
            name='UlanTermType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('name', models.CharField(help_text='Term_Type value for ULAN terms', max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'ULAN Term Type',
                'verbose_name_plural': 'ULAN Term Types',
            },
        ),
        migrations.AddField(
            model_name='ulanterm',
            name='term_type',
            field=models.ForeignKey(blank=True, help_text='Term_Type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.ulantermtype'),
        ),
    ]
