# Generated by Django 6.0 on 2025-12-14 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gc_reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aatassociativerelationship',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='aatassociativerelationshiptype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='aatassociativerelationship',
            name='relationship_type',
            field=models.ForeignKey(blank=True, help_text="Relationship_Type (e.g., 'distinguished from')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associative_relationships', to='gc_reference.aatassociativerelationshiptype'),
        ),
        migrations.AddField(
            model_name='aatnote',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='aatnotecontributor',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='aatnotecontributor',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='gc_reference.aatnote'),
        ),
        migrations.AddField(
            model_name='aatnotesource',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='aatnotesource',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='gc_reference.aatnote'),
        ),
        migrations.AddField(
            model_name='aatparentrelationshiptype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='aatsubject',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='aatsubject',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Preferred parent subject', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='gc_reference.aatsubject', verbose_name='Parent Subject'),
        ),
        migrations.AddField(
            model_name='aatsubject',
            name='parent_relationship_type',
            field=models.ForeignKey(blank=True, help_text="Hier_Rel_Type (e.g., 'Genus/Species-BTG')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.aatparentrelationshiptype', verbose_name='Parent Relationship Type'),
        ),
        migrations.AddField(
            model_name='aatnote',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='gc_reference.aatsubject'),
        ),
        migrations.AddField(
            model_name='aatassociativerelationship',
            name='related_subject',
            field=models.ForeignKey(help_text='VP_Subject_ID for the related concept', on_delete=django.db.models.deletion.CASCADE, related_name='associative_relationships_to', to='gc_reference.aatsubject'),
        ),
        migrations.AddField(
            model_name='aatassociativerelationship',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associative_relationships', to='gc_reference.aatsubject'),
        ),
        migrations.AddField(
            model_name='aatsubjectcontributor',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='aatsubjectcontributor',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_contributors', to='gc_reference.aatsubject'),
        ),
        migrations.AddField(
            model_name='aatsubjectrecordtype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='aatsubject',
            name='record_type',
            field=models.ForeignKey(blank=True, help_text="Record_Type Field (e.g., 'Concept')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.aatsubjectrecordtype', verbose_name='Record Type'),
        ),
        migrations.AddField(
            model_name='aatsubjectsource',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='aatsubjectsource',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_sources', to='gc_reference.aatsubject'),
        ),
        migrations.AddField(
            model_name='aatterm',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='aatterm',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='gc_reference.aatsubject'),
        ),
        migrations.AddField(
            model_name='aattermcontributor',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='aattermcontributor',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='gc_reference.aatterm'),
        ),
        migrations.AddField(
            model_name='aattermsource',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='aattermsource',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='gc_reference.aatterm'),
        ),
        migrations.AddField(
            model_name='isolanguage',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='aatterm',
            name='language_code',
            field=models.ForeignKey(blank=True, help_text="Parsed from language field (e.g., '70051/English')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.isolanguage'),
        ),
        migrations.AddField(
            model_name='aatnote',
            name='note_language',
            field=models.ForeignKey(blank=True, help_text="Parsed from language field (e.g., '70051/English')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.isolanguage'),
        ),
        migrations.AddField(
            model_name='isolanguagescope',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='isolanguage',
            name='iso_language_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languages', to='gc_reference.isolanguagescope', verbose_name='ISO Language Scope'),
        ),
        migrations.AddField(
            model_name='isolanguagetype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='isolanguage',
            name='iso_language_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languages', to='gc_reference.isolanguagetype', verbose_name='ISO Language Type'),
        ),
        migrations.AddField(
            model_name='ulanassociativerelationship',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ulanassociativerelationshiptype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ulanassociativerelationship',
            name='relationship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associative_relationships', to='gc_reference.ulanassociativerelationshiptype'),
        ),
        migrations.AddField(
            model_name='ulanbiography',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ulannationality',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ulannote',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ulannote',
            name='note_language',
            field=models.ForeignKey(blank=True, help_text='Parsed from <Note_Language>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.isolanguage'),
        ),
        migrations.AddField(
            model_name='ulannotecontributor',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ulannotecontributor',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='gc_reference.ulannote'),
        ),
        migrations.AddField(
            model_name='ulannotesource',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ulannotesource',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='gc_reference.ulannote'),
        ),
        migrations.AddField(
            model_name='ulanparentrelationshiptype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ulanpartofspeech',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ulanrole',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ulansubject',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ulansubject',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent_Subject_ID for hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='gc_reference.ulansubject'),
        ),
        migrations.AddField(
            model_name='ulansubject',
            name='parent_relationship_type',
            field=models.ForeignKey(blank=True, help_text='Hier_Rel_Type (e.g. Instance-BTI)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.ulanparentrelationshiptype'),
        ),
        migrations.AddField(
            model_name='ulanrole',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='gc_reference.ulansubject'),
        ),
        migrations.AddField(
            model_name='ulannote',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='gc_reference.ulansubject'),
        ),
        migrations.AddField(
            model_name='ulannationality',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nationalities', to='gc_reference.ulansubject'),
        ),
        migrations.AddField(
            model_name='ulanbiography',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biographies', to='gc_reference.ulansubject'),
        ),
        migrations.AddField(
            model_name='ulanassociativerelationship',
            name='related_subject',
            field=models.ForeignKey(help_text='Related ULAN subject', on_delete=django.db.models.deletion.CASCADE, related_name='associative_relationships_to', to='gc_reference.ulansubject'),
        ),
        migrations.AddField(
            model_name='ulanassociativerelationship',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associative_relationships', to='gc_reference.ulansubject'),
        ),
        migrations.AddField(
            model_name='ulansubjectcontributor',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ulansubjectcontributor',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_contributors', to='gc_reference.ulansubject'),
        ),
        migrations.AddField(
            model_name='ulansubjectrecordtype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ulansubject',
            name='record_type',
            field=models.ForeignKey(blank=True, help_text='Record_Type (e.g., Person, Corporate Body, Family, Group)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.ulansubjectrecordtype'),
        ),
        migrations.AddField(
            model_name='ulansubjectsource',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ulansubjectsource',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_sources', to='gc_reference.ulansubject'),
        ),
        migrations.AddField(
            model_name='ulanterm',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ulanterm',
            name='language_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.isolanguage'),
        ),
        migrations.AddField(
            model_name='ulanterm',
            name='part_of_speech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.ulanpartofspeech'),
        ),
        migrations.AddField(
            model_name='ulanterm',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='gc_reference.ulansubject'),
        ),
        migrations.AddField(
            model_name='ulantermcontributor',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ulantermcontributor',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='gc_reference.ulanterm'),
        ),
        migrations.AddField(
            model_name='ulantermsource',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ulantermsource',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='gc_reference.ulanterm'),
        ),
        migrations.AddField(
            model_name='ulantermtype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ulanterm',
            name='term_type',
            field=models.ForeignKey(blank=True, help_text='Term_Type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gc_reference.ulantermtype'),
        ),
    ]
