# Tailwind-inspired color names for choice fields.
# Use in templates like bg-{{ color }}-300 or text-{{ color }}-600.
TAILWIND_COLOR_CHOICES = [
    ("slate", "Slate"),
    ("gray", "Gray"),
    ("zinc", "Zinc"),
    ("neutral", "Neutral"),
    ("stone", "Stone"),
    ("red", "Red"),
    ("orange", "Orange"),
    ("amber", "Amber"),
    ("yellow", "Yellow"),
    ("lime", "Lime"),
    ("green", "Green"),
    ("emerald", "Emerald"),
    ("teal", "Teal"),
    ("cyan", "Cyan"),
    ("sky", "Sky"),
    ("blue", "Blue"),
    ("indigo", "Indigo"),
    ("violet", "Violet"),
    ("purple", "Purple"),
    ("fuchsia", "Fuchsia"),
    ("pink", "Pink"),
    ("rose", "Rose"),
]
